version: '3.8'
services:
  akhq:
    image: tchiotludo/akhq:0.26.0
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server-1:
              properties:
                bootstrap.servers: "kafka:29092"
    ports:
      - 8082:8080
  kafka:
    image: confluentinc/cp-kafka:8.0.3
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Unique ID for this node in the cluster
      KAFKA_NODE_ID: 1
      # Roles this node plays: broker (handles data) and controller (manages cluster state)
      KAFKA_PROCESS_ROLES: broker,controller
      # The listeners for client connections and internal controller communication
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      # How clients (like your Spring app) and other brokers should reach this node
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      # Mapping protocol names to security protocols
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # The listener used for controller communication
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # The listener used for inter-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # The voters in the consensus quorum (pointing to itself for a single node)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      # A static Cluster ID required for KRaft to start (Base64 encoded UUID)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      # Required to initialize the cluster storage with a specific ID
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'