spring:
  application:
    name: kafka-streams-protobuf
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      state-dir: ${USERPROFILE}\kafka-local-state
    properties:
      schema.registry.url: http://localhost:8081

server:
  port: 7072
